server:
  port: 8088

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: user_route
          uri: https://6bbd-73-63-240-26.ngrok-free.app/api
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /user/$\{segment}

        - id: product_route
          uri: https://6bbd-73-63-240-26.ngrok-free.app/api
          predicates:
            - Path=/products/{id}, /products, /products/upload
          filters:
            - RewritePath=/products/(?<segment>.*), /products/$\{segment}

        - id: imageupload_route
          uri: https://6bbd-73-63-240-26.ngrok-free.app/api
          predicates:
            - Path=/image-upload/**
          filters:
            - RewritePath=/image-upload/(?<segment>.*), /image-upload/$\{segment}

        - id: recommendation_route
          uri: https://42fc-209-129-244-192.ngrok-free.app/api
          predicates:
            - Path=/recommendations/**
          filters:
            - RewritePath=/recommendations/(?<segment>.*), /recommendations/$\{segment}

        - id: saveview_route
          uri: https://42fc-209-129-244-192.ngrok-free.app
          predicates:
            - Path=/interactions/**
          filters:
            - RewritePath=/interactions/(?<segment>.*), /interactions/$\{segment}

        - id: chat_route
          uri: http://172.29.94.150:8081
          predicates:
            - Path=/products/chat
          filters:
            - RewritePath=/products/chat/(?<segment>.*), /products/chat/$\{segment}

        - id: payment_route
          uri: http://172.20.215.68:8090
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment/(?<segment>.*), /payment/$\{segment}

        - id: account_route
          uri: http://172.20.215.68:8090
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<segment>.*), /account/$\{segment}

        - id: orders_route
          uri: http://172.29.93.142:8088
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /orders/$\{segment}

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace